---
- name: Configure AWS EC2 instance
  hosts: BACKEND
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    SECRET_FILE: "{{ SECRET_FILE }}"
  roles:
    - role: common
    - role: setup
