---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: Install Python 3, pip, and six
  apt:
    name:
      - python3
      - python3-pip
      - python3-six
    state: present