version: 2
jobs:
  backend_build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            pip install -r backend/requirements.txt


  backend_deploy:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push to Docker Hub
          command: |
            docker build -t tomlui2010/$IMAGE_NAME:latest .
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push tomlui2010/$IMAGE_NAME:latest
      - run:
          name: Create secrets env file
          command: |
            echo "SECRET_FILE=${secrets}" > secrets.env



workflows:
  version: 2
  backend:
    jobs:
      - backend_build
      - backend_deploy:
          requires:
            - backend_build
          context:
            - ppp